# ============================================================
#  Mosquitto Configuration — Eclipse Mosquitto 2.x
# ============================================================

# Listener padrão (sem TLS)
listener 1883
protocol mqtt

# WebSocket (opcional — útil para debug via browser)
listener 9001
protocol websockets

# Segurança básica
allow_anonymous false
password_file /mosquitto/config/passwordfile_local
acl_file /mosquitto/config/aclfile

# Persistência
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest stdout
log_type all
